samples: samples.tsv
units: units.tsv



params:
  general:
    PRJEB21971:
      runTable:
        file: 'PRJEB21971_RunTable.txt'
        selected_columns: ['Alias', 'Assay Type', 'Run']
        aggregate_column: 'condition'
        chip_input_value: 'none'
  hicexplorer:
    genome_fasta:
      shiny: ""
      gdu: "/home/skurscheid/Data/References/Genomes/Homo_sapiens/GRCh38_ensembl84/genome.fa"
  bowtie2:
    cli_params: "--reorder --local --rdg 6,4 --rfg 6,4"
    index:
      shiny: ""
      gdu: "/home/skurscheid/Data/References/Genomes/Homo_sapiens/GRCh38_ensembl84/canonical/index/hg38_ensembl84"
  fastp: ""
